# Generated by Django 5.0.3 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Homepage_work',
                'verbose_name_plural': 'Homepage_works',
            },
        ),
        migrations.CreateModel(
            name='work_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order')),
                ('icon', models.ImageField(upload_to='work_department/%Y/%m/%d')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
