# Generated by Django 5.0.3 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Homepage_Team',
                'verbose_name_plural': 'Homepage_Teams',
            },
        ),
        migrations.CreateModel(
            name='Homepage_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Homepage_Testimonial',
                'verbose_name_plural': 'Homepage_Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(verbose_name='order')),
                ('image', models.ImageField(upload_to='Team/%Y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('about_the_worker', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(verbose_name='order')),
                ('image', models.ImageField(upload_to='Testimonial/%Y/%m/%d')),
                ('name', models.CharField(max_length=50)),
                ('information', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
