# Generated by Django 5.0.3 on 2024-03-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
